# Generated by Django 5.0.6 on 2024-06-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoachModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('specialty', models.CharField(choices=[('Batting', 'Batting'), ('Bowling', 'Bowling'), ('FieldCoach', 'FiledCoach'), ('Psyhsio', 'Psyhsio')], default=None, max_length=20)),
                ('profile_pic', models.ImageField(blank=True, default='demo.jpg', null=True, upload_to='Coach')),
                ('experience', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('high_score', models.BigIntegerField(default=0)),
                ('high_wic', models.IntegerField(default=0)),
                ('specialty', models.CharField(choices=[('Batting', 'Batting'), ('Bowling', 'Bowling'), ('AllRounder', 'AllRounder')], default=None, max_length=20)),
                ('profile_pic', models.ImageField(blank=True, default='demo.jpg', null=True, upload_to='Players')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
