# Generated by Django 5.0.6 on 2024-06-16 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cric_Mgnt', '0003_playersmodel_matches_played'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coachmodel',
            name='experience',
            field=models.CharField(max_length=15),
        ),
    ]
